### ISSUE TITLE
Archotech vanilla item defs should be patched

### ISSUE THREAD

**Issue by GingerAvalanche** [MahmudinPURE/MedicalSystemExpansion#1]
Currently, Archotech vanilla item defs are overridden. The downside to this is that it also overrides any changes to those defs by other mods, including ones that would normally be compatible.

By instead patching those defs, we can ensure that this mod's changes take precedence (based on load order) but any other mods' changes to properties this mod doesn't touch are preserved.

**Comment by GingerAvalanche** [comment]
The problem with my previous pull request was that I was changing the parent of a vanilla Def to be a mod-added Def. Mod Defs are loaded after vanilla Defs, and XML is read top-down.

Solution is to patch this mod’s parent Def in before the vanilla Defs that will use it. Will also leave comments in its original declaration location explaining where it’s been moved to.

**Comment by mahmudindev** [comment]
I still not sure about what you mean, but what about this

I make it still overwrite vanilla but not add any new tags.

	<ThingDef ParentName="MSE_BodyPartArchotech">
		<defName>ArchotechEye</defName>
		<label>archotech eye</label>
		<description>An artifical eye built by an archotech. It perceives every type of electromagnetic radiation, including radio waves, infrared, light, x-rays, and gamma rays. Its visual acuity is precise enough to read handwriting from twenty meters away. It can emit various wavelengths of radiation like a flashlight, and has an internal subpersona AI which helps highlight useful visual information. Externally, it looks like a natural human eye, except it can change color at will.</description>
		<statBases>
			<MarketValue>2800</MarketValue>
			<Mass>0.3</Mass>
		</statBases>
	</ThingDef>

	<ThingDef ParentName="MSE_BodyPartArchotech">
		<defName>ArchotechArm</defName>
		<label>archotech arm</label>
		<description>An artifical arm built by an archotech. It's strong enough to crush a thick hardwood branch in its hand, and precise enough to write a sonnet on a grain of rice. It looks and feels like natural flesh, but it's harder to damage than plasteel. Even if it is harmed, it repairs itself over time.</description>
		<statBases>
			<MarketValue>2800</MarketValue>
			<Mass>4</Mass>
		</statBases>
	</ThingDef>

	<ThingDef ParentName="MSE_BodyPartArchotech">
		<defName>ArchotechLeg</defName>
		<label>archotech leg</label>
		<description>An artifical leg built by an archotech. It looks and feels like natural flesh, but a pair of these can move the user as fast as a decent car, and it's harder to damage than plasteel. Even if it is harmed, it repairs itself over time.</description>
		<statBases>
			<MarketValue>2800</MarketValue>
			<Mass>7</Mass>
		</statBases>
	</ThingDef>

Then patching it

<Patch>

	<Operation Class="PatchOperationConditional">
		<xpath>*/ThingDef[defName = "ArchotechEye"]/costList</xpath>
		<match Class="PatchOperationReplace">
			<xpath>*/ThingDef[defName = "ArchotechEye"]/costList</xpath>
			<value>
				<costList>
					<Uranium>30</Uranium>
					<Gold>40</Gold>
					<Plasteel>15</Plasteel>
					<ComponentSpacer>8</ComponentSpacer>
				</costList>
			</value>
		</match>
		<nomatch Class="PatchOperationAdd">
			<xpath>*/ThingDef[defName = "ArchotechEye"]</xpath>
			<value>
				<costList>
					<Uranium>30</Uranium>
					<Gold>40</Gold>
					<Plasteel>15</Plasteel>
					<ComponentSpacer>8</ComponentSpacer>
				</costList>
			</value>
		</nomatch>
	</Operation>
	<Operation Class="PatchOperationConditional">
		<xpath>*/ThingDef[defName = "ArchotechEye"]/statBases/WorkToMake</xpath>
		<match Class="PatchOperationReplace">
			<xpath>*/ThingDef[defName = "ArchotechEye"]/statBases/WorkToMake</xpath>
			<value>
				<WorkToMake>114000</WorkToMake>
			</value>
		</match>
		<nomatch Class="PatchOperationAdd">
			<xpath>*/ThingDef[defName = "ArchotechEye"]/statBases</xpath>
			<value>
				<WorkToMake>114000</WorkToMake>
			</value>
		</nomatch>
	</Operation>
	<Operation Class="PatchOperationSequence">
		<success>Always</success>
		<operations>
			<li Class="PatchOperationTest">
				<xpath>*/ThingDef[defName = "ArchotechEye"]/thingSetMakerTags</xpath>
				<success>Invert</success>
			</li>
			<li Class="PatchOperationRemove">
				<xpath>*/ThingDef[defName = "ArchotechEye"]/thingSetMakerTags</xpath>
			</li>
		</operations>
	</Operation>

	<Operation Class="PatchOperationConditional">
		<xpath>*/ThingDef[defName = "ArchotechArm"]/costList</xpath>
		<match Class="PatchOperationReplace">
			<xpath>*/ThingDef[defName = "ArchotechArm"]/costList</xpath>
			<value>
				<costList>
					<Uranium>50</Uranium>
					<Gold>25</Gold>
					<Plasteel>35</Plasteel>
					<ComponentSpacer>8</ComponentSpacer>
				</costList>
			</value>
		</match>
		<nomatch Class="PatchOperationAdd">
			<xpath>*/ThingDef[defName = "ArchotechArm"]</xpath>
			<value>
				<costList>
					<Uranium>50</Uranium>
					<Gold>25</Gold>
					<Plasteel>35</Plasteel>
					<ComponentSpacer>8</ComponentSpacer>
				</costList>
			</value>
		</nomatch>
	</Operation>
	<Operation Class="PatchOperationConditional">
		<xpath>*/ThingDef[defName = "ArchotechArm"]/statBases/WorkToMake</xpath>
		<match Class="PatchOperationReplace">
			<xpath>*/ThingDef[defName = "ArchotechArm"]/statBases/WorkToMake</xpath>
			<value>
				<WorkToMake>78000</WorkToMake>
			</value>
		</match>
		<nomatch Class="PatchOperationAdd">
			<xpath>*/ThingDef[defName = "ArchotechArm"]/statBases</xpath>
			<value>
				<WorkToMake>78000</WorkToMake>
			</value>
		</nomatch>
	</Operation>
	<Operation Class="PatchOperationSequence">
		<success>Always</success>
		<operations>
			<li Class="PatchOperationTest">
				<xpath>*/ThingDef[defName = "ArchotechArm"]/thingSetMakerTags</xpath>
				<success>Invert</success>
			</li>
			<li Class="PatchOperationRemove">
				<xpath>*/ThingDef[defName = "ArchotechArm"]/thingSetMakerTags</xpath>
			</li>
		</operations>
	</Operation>

	<Operation Class="PatchOperationConditional">
		<xpath>*/ThingDef[defName = "ArchotechLeg"]/costList</xpath>
		<match Class="PatchOperationReplace">
			<xpath>*/ThingDef[defName = "ArchotechLeg"]/costList</xpath>
			<value>
				<costList>
					<Uranium>50</Uranium>
					<Gold>25</Gold>
					<Plasteel>35</Plasteel>
					<ComponentSpacer>8</ComponentSpacer>
				</costList>
			</value>
		</match>
		<nomatch Class="PatchOperationAdd">
			<xpath>*/ThingDef[defName = "ArchotechLeg"]</xpath>
			<value>
				<costList>
					<Uranium>50</Uranium>
					<Gold>25</Gold>
					<Plasteel>35</Plasteel>
					<ComponentSpacer>8</ComponentSpacer>
				</costList>
			</value>
		</nomatch>
	</Operation>
	<Operation Class="PatchOperationConditional">
		<xpath>*/ThingDef[defName = "ArchotechLeg"]/statBases/WorkToMake</xpath>
		<match Class="PatchOperationReplace">
			<xpath>*/ThingDef[defName = "ArchotechLeg"]/statBases/WorkToMake</xpath>
			<value>
				<WorkToMake>78000</WorkToMake>
			</value>
		</match>
		<nomatch Class="PatchOperationAdd">
			<xpath>*/ThingDef[defName = "ArchotechLeg"]/statBases</xpath>
			<value>
				<WorkToMake>78000</WorkToMake>
			</value>
		</nomatch>
	</Operation>
	<Operation Class="PatchOperationSequence">
		<success>Always</success>
		<operations>
			<li Class="PatchOperationTest">
				<xpath>*/ThingDef[defName = "ArchotechLeg"]/thingSetMakerTags</xpath>
				<success>Invert</success>
			</li>
			<li Class="PatchOperationRemove">
				<xpath>*/ThingDef[defName = "ArchotechLeg"]/thingSetMakerTags</xpath>
			</li>
		</operations>
	</Operation>

</Patch>

**Comment by mahmudindev** [comment]
I forget to add a check of parent name before patching. So make it don't patching if parent is not "MSE_BodyPartArchotech".

**Comment by GingerAvalanche** [comment]
The version in my fork's master branch is currently working and does the patching properly. It patches MSE_BodyPartArchotech in below BodyPartArchotechBase (which it needs to be below) and right above ArchotechEye (which it needs to be above) so everything loads into the game and runs.

The only issue is that when starting up the game, it gives the error `XML error: Could not register node named "MSE_BodyPartArchotech" because this name is already used.` This doesn't stop the game from running, and everything works like it should, but it pops up the debug log, which we don't want. I haven't figured out how to fix this.

I don't know why it does this, since MSE_BodyPartArchotech is only created once. You can see that I test to see if a ThingDef with that name already exists before I try to insert it.
```
 	<Operation Class="PatchOperationSequence">
		<success>Always</success>
		<operations>
			<li Class="PatchOperationTest">
				<xpath>*/ThingDef[@Name = "MSE_BodyPartArchotech"]</xpath>
				<success>Invert</success>
			</li>
			<li Class="PatchOperationInsert">
				<xpath>*/ThingDef[@Name = "BodyPartArchotechBase"]</xpath>
				<value>
					<ThingDef Name="MSE_BodyPartArchotech" ParentName="BodyPartArchotechBase" Abstract="True">
						<recipeMaker>
							<workSpeedStat>SmithingSpeed</workSpeedStat>
							<workSkill>Crafting</workSkill>
							<effectWorking>Smith</effectWorking>
							<soundWorking>MSE_Assembling</soundWorking>
							<recipeUsers>
								<li>ArchotechProsthesesBench</li>
							</recipeUsers>
							<skillRequirements>
								<Crafting>12</Crafting>
							</skillRequirements>
							<unfinishedThingDef>UnfinishedComponent</unfinishedThingDef>
							<researchPrerequisite>MSE_ArchotechCrafting</researchPrerequisite>
						</recipeMaker>
						<techLevel>Archotech</techLevel>
						<thingCategories>
							<li>ArchotechProstheses</li>
						</thingCategories>
						<thingSetMakerTags>
							<li>RewardSpecial</li>
						</thingSetMakerTags>
					</ThingDef>
				</value>
			</li>
		</operations>
	</Operation>
```

**Comment by GingerAvalanche** [comment]
I'm still looking into why the game gives the error `Could not register node named "MSE_BodyPartArchotech" because this name is already used.` There are no problems during actual play.

I'm sorry it's taking so long.

**Comment by mahmudindev** [comment]
I close this issue for now. If you know the better patch the you can reopen this. Thanks for your contribution.
